sudo: required
services:
  - docker
install:
  - docker build -t test-integration-rails:latest .
  - >
    docker run
    -e "CIRCLE_PROJECT_REPONAME=$(echo $TRAVIS_REPO_SLUG | cut -f2 -d '/')"
    -e "CIRCLE_BUILD_NUM=${TRAVIS_BUILD_NUMBER}"
    -e "IMAGE=${IMAGE:-coreos-beta}"
    -e "CHANNEL=${CHANNEL:-development}"
    -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"                                                                                                                                                                                                    
    -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"                                                                                                                                                                                            
    --name=test-integration-rails-init test-integration-rails:latest /initialize.sh
  - docker commit test-integration-rails-init test-integration-rails:latest
script:
  - go build -v
  - docker build -t experimentalplatform/app-manager:$TRAVIS_BRANCH .
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push experimentalplatform/app-manager:$TRAVIS_BRANCH
  - docker run --name=test-integration-rails test-integration-rails:latest /run_tests.sh
after_script:
  - docker run --name=DUMP-test-integration-rails test-integration-rails:latest vagrant ssh -- sudo journalctl
  - docker run --name=DESTROY-test-integration-rails test-integration-rails:latest vagrant destroy -f
