FROM experimentalplatform/ubuntu:latest

RUN apt-get -y update && apt-get -y install openssh-client && rm -rf /var/lib/apt/lists/*

ADD vagrant_1.7.2_x86_64.deb /tmp/vagrant.deb
RUN dpkg -i /tmp/vagrant.deb && \
    rm -rf /tmp/vagrant.deb

RUN vagrant plugin install vagrant-digitalocean
RUN vagrant box add digital_ocean https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box

ADD Vagrantfile /Vagrantfile
ADD cloud-config.yaml /cloud-config.yaml

ADD initialize.sh /initialize.sh
ADD run_tests.sh /run_tests.sh
RUN chmod 755 /initialize.sh /run_tests.sh

RUN mkdir -p /.ssh && ssh-keygen -C "autogenerated $(date)" -V "+2h" -N "" -f /.ssh/id_rsa
RUN cp -a /.ssh /root/

CMD [ "/bin/bash" ]